const CookieExample = ({format}) => {
    return (
        <>
            {
                format === "header_string" && (
                    <p className={`text-gray-800 mb-0`}>_ga=GA1.2.123456789.987654321;
                        PHPSESSID=28f2d88ee9322cfd2e4f1e; csrftoken=abcdef123456; logged_in=true</p>
                )
            }

            {
                format === "json" && (
                    <pre>{JSON.stringify([{
                        "name": "sessionId",
                        "value": "abc123xyz456",
                        "domain": ".example.com",
                        "path": "/",
                        "secure": true,
                        "httpOnly": true,
                        "sameSite": "Lax",
                        "expirationDate": 1713543600,
                        "storeId": "0"
                    }], null, 2)}</pre>
                )
            }

            {
                format === "netscape" && (
                    <>
                        <p className={`text-gray-600`}># Netscape HTTP Cookie File</p>
                        <p className={`text-gray-600`}># This file was generated by some tool</p>
                        <p className={`text-gray-600`}># http://curl.haxx.se/rfc/cookie_spec.html</p>
                        <p className={`text-gray-600 mb-3`}># This is a generated file! Do not edit.</p>
                        <p className={`text-gray-900`}>{`.example.com\tTRUE\t/\tFALSE\t1713543600\tsessionId\tvalue`}</p>
                    </>
                )
            }
        </>
    )
}

export default CookieExample